MT_DATA = {
    "MT103": {
        "category": "1",
        "name": "Single Customer Credit Transfer",
        "description": "개별 고객의 국제 전신 송금용 표준 결제 메시지",
        "required_fields": [":20", ":23B", ":32A", ":50", ":59", ":71A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference Number",
                "length": "16x",
                "description": "각 은행에서 생성되는 고유 참조 번호",
                "required": True,
            },
            {
                "field": ":23B",
                "name": "Bank Operation Code",
                "length": "4!c",
                "description": "작업 유형 지정 (CRED/SPAY/SSTD/SPRI)",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Interbank Settled",
                "length": "6!n3!a15d",
                "description": "결제일/통화/은행간 정산 금액",
                "required": True,
            },
            {
                "field": ":33B",
                "name": "Currency / Original Ordered Amount",
                "length": "3!a15d",
                "description": "원래 주문 금액 (통화 변환 시)",
                "required": False,
            },
            {
                "field": ":50K",
                "name": "Ordering Customer",
                "length": "A, F, or K",
                "description": "주문 고객 (송금인) 정보",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관 (송금인 은행)",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인의 대리은행",
                "required": False,
            },
            {
                "field": ":54A",
                "name": "Receiver's Correspondent",
                "length": "A, B, or D",
                "description": "수신자의 대리은행",
                "required": False,
            },
            {
                "field": ":56A",
                "name": "Intermediary",
                "length": "A, C, or D",
                "description": "중개 은행",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "수혜자 은행 정보",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자 정보",
                "required": True,
            },
            {
                "field": ":70",
                "name": "Remittance Information",
                "length": "4*35x",
                "description": "송금 정보",
                "required": False,
            },
            {
                "field": ":71A",
                "name": "Details of Charges",
                "length": "3!a",
                "description": "수수료 부담 방식 (BEN/OUR/SHA)",
                "required": True,
            },
            {
                "field": ":72",
                "name": "Sender to Receiver Information",
                "length": "6*35x",
                "description": "송금人对수신은행 정보",
                "required": False,
            },
            {
                "field": ":77B",
                "name": "Regulatory Reporting",
                "length": "3*35x",
                "description": "규제 보고",
                "required": False,
            },
        ],
    },
    "MT202": {
        "category": "2",
        "name": "Financial Institution Transfer",
        "description": "금융기관 간 거래 명령 메시지",
        "required_fields": [":20", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조 번호",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":54A",
                "name": "Receiver's Correspondent",
                "length": "A, B, or D",
                "description": "수신자 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
            {
                "field": ":72",
                "name": "Sender to Receiver Information",
                "length": "6*35x",
                "description": "송금人对수신자 정보",
                "required": False,
            },
        ],
    },
    "MT202COV": {
        "category": "2",
        "name": "Financial Institution Transfer - Cover",
        "description": "금융기관 간 커버 결제 메시지",
        "required_fields": [":20", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조 번호",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":54A",
                "name": "Receiver's Correspondent",
                "length": "A, B, or D",
                "description": "수신자 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
            {
                "field": ":72",
                "name": "Sender to Receiver Information",
                "length": "6*35x",
                "description": "송금人对수신자 정보",
                "required": False,
            },
        ],
    },
    "MT101": {
        "category": "1",
        "name": "Request for Transfer",
        "description": "고객의 송금 요청 메시지",
        "required_fields": [":20", ":32A", ":50K", ":59"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference Number",
                "length": "16x",
                "description": "트랜잭션 참조 번호",
                "required": True,
            },
            {
                "field": ":23",
                "name": "Bank Operation Code",
                "length": "4!c",
                "description": "은행 작업 코드",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Ordering Customer",
                "length": "A, F, or K",
                "description": "주문 고객",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자",
                "required": True,
            },
            {
                "field": ":70",
                "name": "Remittance Information",
                "length": "4*35x",
                "description": "송금 정보",
                "required": False,
            },
            {
                "field": ":71A",
                "name": "Details of Charges",
                "length": "3!a",
                "description": "수수료 상세",
                "required": False,
            },
        ],
    },
    "MT102": {
        "category": "1",
        "name": "Multiple Customer Credit Transfer",
        "description": "여러 고객 신용 전송 메시지",
        "required_fields": [":20", ":32A", ":50K"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference Number",
                "length": "16x",
                "description": "트랜잭션 참조 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Payment Relation Number",
                "length": "16x",
                "description": "결제 관계 번호",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/총액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Ordering Customer",
                "length": "A, F, or K",
                "description": "주문 고객",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
        ],
    },
    "MT102Plus": {
        "category": "1",
        "name": "Multiple Customer Credit Transfer Plus",
        "description": "여러 고객 신용 전송 플러스",
        "required_fields": [":20", ":32A", ":50K"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference Number",
                "length": "16x",
                "description": "트랜잭션 참조 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Payment Relation Number",
                "length": "16x",
                "description": "결제 관계 번호",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/총액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Ordering Customer",
                "length": "A, F, or K",
                "description": "주문 고객",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
        ],
    },
    "MT107": {
        "category": "1",
        "name": "Cash Payment",
        "description": "현금 결제 메시지",
        "required_fields": [":20", ":32A", ":50K", ":59"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Ordering Customer",
                "length": "A, F, or K",
                "description": "주문 고객",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary Customer",
                "length": "No letter, A, or F",
                "description": "수혜 고객",
                "required": True,
            },
            {
                "field": ":70",
                "name": "Remittance Information",
                "length": "4*35x",
                "description": "송금 정보",
                "required": False,
            },
        ],
    },
    "MT110": {
        "category": "1",
        "name": "Cheque",
        "description": "수표 메시지",
        "required_fields": [":20", ":21", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Cheque Number",
                "length": "6!n",
                "description": "수표 번호",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Drawer",
                "length": "A, F, or K",
                "description": "발행인",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Drawee Bank",
                "length": "A or D",
                "description": "지급 은행",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Collecting Bank",
                "length": "A, B, or D",
                "description": "수금 은행",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Payee Bank",
                "length": "A, B, C, or D",
                "description": "수취 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Payee",
                "length": "No letter, A, or F",
                "description": "수취인",
                "required": False,
            },
        ],
    },
    "MT111": {
        "category": "1",
        "name": "Request for Payment Collection",
        "description": "수금 청구 요청 메시지",
        "required_fields": [":20", ":32A", ":50K"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Drawer",
                "length": "A, F, or K",
                "description": "발행인",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Drawee Bank",
                "length": "A or D",
                "description": "지급 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Payee",
                "length": "No letter, A, or F",
                "description": "수취인",
                "required": False,
            },
        ],
    },
    "MT205": {
        "category": "2",
        "name": "Financial Institution Netting",
        "description": "금융기관 순차 결제 메시지",
        "required_fields": [":20", ":30", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":30",
                "name": "Date of netting",
                "length": "8!n",
                "description": "순차 날짜",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
        ],
    },
    "MT205COV": {
        "category": "2",
        "name": "Financial Institution Netting - Cover",
        "description": "금융기관 순차 결제 커버 메시지",
        "required_fields": [":20", ":30", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":30",
                "name": "Date of netting",
                "length": "8!n",
                "description": "순차 날짜",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Ordering Institution",
                "length": "A or D",
                "description": "주문 기관",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Sender's Correspondent",
                "length": "A, B, or D",
                "description": "송금인 대리인",
                "required": False,
            },
            {
                "field": ":57A",
                "name": "Account with Institution",
                "length": "A, B, C, or D",
                "description": "계좌 기관",
                "required": False,
            },
        ],
    },
    "MT300": {
        "category": "3",
        "name": "Foreign Exchange Deal",
        "description": "외환 거래 메시지",
        "required_fields": [":20", ":22A", ":32B"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":22A",
                "name": "Type of Operation",
                "length": "4!c",
                "description": "거래 유형",
                "required": True,
            },
            {
                "field": ":22C",
                "name": "Currency",
                "length": "3!a",
                "description": "통화",
                "required": False,
            },
            {
                "field": ":82A",
                "name": "Dealer",
                "length": "A or D",
                "description": "딜러",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Deal Amount",
                "length": "3!a15d",
                "description": "거래 금액",
                "required": True,
            },
            {
                "field": ":36",
                "name": "Exchange Rate",
                "length": "12d",
                "description": "환율",
                "required": False,
            },
        ],
    },
    "MT303": {
        "category": "3",
        "name": "FX Option Confirmation",
        "description": "외환 옵션 확인 메시지",
        "required_fields": [":20", ":22A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":22A",
                "name": "Type of Operation",
                "length": "4!c",
                "description": "거래 유형",
                "required": True,
            },
            {
                "field": ":22C",
                "name": "Currency Pair",
                "length": "6!n",
                "description": "통화쌍",
                "required": False,
            },
            {
                "field": ":82A",
                "name": "Dealer",
                "length": "A or D",
                "description": "딜러",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Deal Amount",
                "length": "3!a15d",
                "description": "거래 금액",
                "required": False,
            },
        ],
    },
    "MT320": {
        "category": "3",
        "name": "Fixed Loan Contract",
        "description": "고정 대출 계약 메시지",
        "required_fields": [":20", ":22A", ":32B"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":22A",
                "name": "Type of Operation",
                "length": "4!c",
                "description": "거래 유형",
                "required": True,
            },
            {
                "field": ":32B",
                "name": "Principal Amount",
                "length": "3!a15d",
                "description": "원금",
                "required": True,
            },
            {
                "field": ":30",
                "name": "Date of Settlement",
                "length": "8!n",
                "description": "결제일",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Borrower",
                "length": "A or D",
                "description": "차입자",
                "required": False,
            },
        ],
    },
    "MT330": {
        "category": "3",
        "name": "Call Money Notice",
        "description": "콜머니 고지 메시지",
        "required_fields": [":20", ":32B"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Amount",
                "length": "3!a15d",
                "description": "금액",
                "required": True,
            },
            {
                "field": ":30",
                "name": "Date",
                "length": "8!n",
                "description": "날짜",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "From",
                "length": "A or D",
                "description": "송신",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "To",
                "length": "A, B, or D",
                "description": "수신",
                "required": False,
            },
        ],
    },
    "MT340": {
        "category": "3",
        "name": "Short Term Deposit",
        "description": "단기 예금 메시지",
        "required_fields": [":20", ":32B"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Amount",
                "length": "3!a15d",
                "description": "금액",
                "required": True,
            },
            {
                "field": ":30",
                "name": "Date",
                "length": "8!n",
                "description": "날짜",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "From",
                "length": "A or D",
                "description": "송신",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "To",
                "length": "A, B, or D",
                "description": "수신",
                "required": False,
            },
        ],
    },
    "MT400": {
        "category": "4",
        "name": "Cheque / Payment Order",
        "description": "수표/결제 지시 메시지",
        "required_fields": [":20", ":21", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Cheque Number",
                "length": "6!n",
                "description": "수표 번호",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
            {
                "field": ":50K",
                "name": "Drawer",
                "length": "A, F, or K",
                "description": "발행인",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Drawee Bank",
                "length": "A or D",
                "description": "지급 은행",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Collecting Bank",
                "length": "A, B, or D",
                "description": "수금 은행",
                "required": False,
            },
        ],
    },
    "MT410": {
        "category": "4",
        "name": "Notice of Attachment",
        "description": "압류 고지 메시지",
        "required_fields": [":20", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":32A",
                "name": "Amount",
                "length": "6!n3!a15d",
                "description": "금액",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Creditor",
                "length": "A or D",
                "description": "채권자",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Debtor",
                "length": "A, B, or D",
                "description": "채무자",
                "required": False,
            },
        ],
    },
    "MT506": {
        "category": "5",
        "name": "Securities Settlement",
        "description": "증권 정산 메시지",
        "required_fields": [":20", ":22C"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":22C",
                "name": "Transaction Type",
                "length": "4!c",
                "description": "거래 유형",
                "required": True,
            },
            {
                "field": ":35B",
                "name": "Identification of Financial Instrument",
                "length": "ISIN",
                "description": "금융상품 식별",
                "required": False,
            },
            {
                "field": ":36",
                "name": "Quantity",
                "length": "4!n15d",
                "description": "수량",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Amount",
                "length": "3!a15d",
                "description": "금액",
                "required": False,
            },
            {
                "field": ":53A",
                "name": "Settlement Party",
                "length": "A, B, or D",
                "description": "정산 당사자",
                "required": False,
            },
        ],
    },
    "MT509": {
        "category": "5",
        "name": "Securities Settlement Confirmation",
        "description": "증권 정산 확인 메시지",
        "required_fields": [":20", ":22C"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":22C",
                "name": "Transaction Type",
                "length": "4!c",
                "description": "거래 유형",
                "required": True,
            },
            {
                "field": ":35B",
                "name": "Identification of Financial Instrument",
                "length": "ISIN",
                "description": "금융상품 식별",
                "required": False,
            },
            {
                "field": ":36",
                "name": "Quantity",
                "length": "4!n15d",
                "description": "수량",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Amount",
                "length": "3!a15d",
                "description": "금액",
                "required": False,
            },
        ],
    },
    "MT515": {
        "category": "5",
        "name": "Corporate Action",
        "description": "기업 행위 메시지",
        "required_fields": [":20", ":22C"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":22C",
                "name": "Corporate Action Type",
                "length": "4!c",
                "description": "기업 행위 유형",
                "required": True,
            },
            {
                "field": ":35B",
                "name": "Identification of Financial Instrument",
                "length": "ISIN",
                "description": "금융상품 식별",
                "required": False,
            },
            {
                "field": ":16R",
                "name": "Corporate Action Details",
                "length": "x",
                "description": "기업 행위 상세",
                "required": False,
            },
        ],
    },
    "MT600": {
        "category": "6",
        "name": "Trade Services",
        "description": "무역 서비스 메시지",
        "required_fields": [":20"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":22C",
                "name": "Type of Trade Service",
                "length": "4!c",
                "description": "무역 서비스 유형",
                "required": False,
            },
        ],
    },
    "MT700": {
        "category": "7",
        "name": "Issue of Documentary Credit",
        "description": "신용장 개설 메시지",
        "required_fields": [":20", ":31D", ":50", ":59", ":32B"],
        "fields": [
            {
                "field": ":20",
                "name": "Documentary Credit Number",
                "length": "16x",
                "description": "신용장 번호",
                "required": False,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":23",
                "name": "Bank Reference",
                "length": "16x",
                "description": "은행 참조",
                "required": False,
            },
            {
                "field": ":31D",
                "name": "Date and Place of Expiry",
                "length": "6!n2!a2!a",
                "description": "만기일/장소",
                "required": True,
            },
            {
                "field": ":51A",
                "name": "Applicant Bank",
                "length": "A",
                "description": "개설 은행",
                "required": False,
            },
            {
                "field": ":50",
                "name": "Applicant",
                "length": "A, F, or K",
                "description": "申请人",
                "required": True,
            },
            {
                "field": ":52A",
                "name": "Issuing Bank",
                "length": "A or D",
                "description": "발행 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자",
                "required": True,
            },
            {
                "field": ":32B",
                "name": "Documentary Credit Amount",
                "length": "3!a15d",
                "description": "신용장 금액",
                "required": True,
            },
            {
                "field": ":41",
                "name": "Available With",
                "length": "A, D, or K",
                "description": "사용 가능",
                "required": False,
            },
        ],
    },
    "MT707": {
        "category": "7",
        "name": "Amendment of Documentary Credit",
        "description": "신용장 수정 메시지",
        "required_fields": [":20"],
        "fields": [
            {
                "field": ":20",
                "name": "Documentary Credit Number",
                "length": "16x",
                "description": "신용장 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":23",
                "name": "Bank Reference",
                "length": "16x",
                "description": "은행 참조",
                "required": False,
            },
            {
                "field": ":31D",
                "name": "New Date of Expiry",
                "length": "6!n2!a2!a",
                "description": "새 만기일",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Issuing Bank",
                "length": "A or D",
                "description": "발행 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자",
                "required": False,
            },
        ],
    },
    "MT710": {
        "category": "7",
        "name": "Advice of Documentary Credit",
        "description": "신용장 통지 메시지",
        "required_fields": [":20", ":59"],
        "fields": [
            {
                "field": ":20",
                "name": "Documentary Credit Number",
                "length": "16x",
                "description": "신용장 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Issuing Bank",
                "length": "A or D",
                "description": "발행 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자",
                "required": True,
            },
            {
                "field": ":32B",
                "name": "Documentary Credit Amount",
                "length": "3!a15d",
                "description": "신용장 금액",
                "required": False,
            },
        ],
    },
    "MT720": {
        "category": "7",
        "name": "Transfer of Documentary Credit",
        "description": "신용장 양도 메시지",
        "required_fields": [":20", ":59"],
        "fields": [
            {
                "field": ":20",
                "name": "Documentary Credit Number",
                "length": "16x",
                "description": "신용장 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":52A",
                "name": "Transferring Bank",
                "length": "A or D",
                "description": "양도 은행",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Second Beneficiary",
                "length": "No letter, A, or F",
                "description": "제2수혜자",
                "required": True,
            },
        ],
    },
    "MT760": {
        "category": "7",
        "name": "Guarantee",
        "description": "보증서 메시지",
        "required_fields": [":20", ":22A"],
        "fields": [
            {
                "field": ":20",
                "name": "Guarantee Number",
                "length": "16x",
                "description": "보증서 번호",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":22A",
                "name": "Type of Guarantee",
                "length": "4!c",
                "description": "보증 유형",
                "required": True,
            },
            {
                "field": ":50",
                "name": "Applicant",
                "length": "A, F, or K",
                "description": "申请人",
                "required": False,
            },
            {
                "field": ":59",
                "name": "Beneficiary",
                "length": "No letter, A, or F",
                "description": "수혜자",
                "required": False,
            },
            {
                "field": ":32B",
                "name": "Guarantee Amount",
                "length": "3!a15d",
                "description": "보증 금액",
                "required": False,
            },
        ],
    },
    "MT900": {
        "category": "9",
        "name": "Confirmation of Debit",
        "description": "차변 확인 메시지",
        "required_fields": [":20", ":25", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":25",
                "name": "Account Identification",
                "length": "35x",
                "description": "계좌 식별",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
        ],
    },
    "MT910": {
        "category": "9",
        "name": "Confirmation of Credit",
        "description": "대변 확인 메시지",
        "required_fields": [":20", ":25", ":32A"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":25",
                "name": "Account Identification",
                "length": "35x",
                "description": "계좌 식별",
                "required": True,
            },
            {
                "field": ":32A",
                "name": "Value Date / Currency / Amount",
                "length": "6!n3!a15d",
                "description": "결제일/통화/금액",
                "required": True,
            },
        ],
    },
    "MT940": {
        "category": "9",
        "name": "Customer Statement",
        "description": "고객 명세서 메시지",
        "required_fields": [":20", ":25", ":28C"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":25",
                "name": "Account Identification",
                "length": "35x",
                "description": "계좌 식별",
                "required": True,
            },
            {
                "field": ":28C",
                "name": "Statement Number",
                "length": "5n",
                "description": "명세서 번호",
                "required": True,
            },
            {
                "field": ":31D",
                "name": "Statement Date",
                "length": "8!n",
                "description": "명세서 날짜",
                "required": False,
            },
            {
                "field": ":60",
                "name": "Opening Balance",
                "length": "3!a15d",
                "description": "시작 잔액",
                "required": False,
            },
            {
                "field": ":61",
                "name": "Statement Line",
                "length": "6!n3!a15d",
                "description": "명세서 라인",
                "required": False,
            },
            {
                "field": ":62",
                "name": "Closing Balance",
                "length": "3!a15d",
                "description": "종료 잔액",
                "required": False,
            },
        ],
    },
    "MT950": {
        "category": "9",
        "name": "Customer Statement Message",
        "description": "고객 명세서 메시지",
        "required_fields": [":20", ":25"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":25",
                "name": "Account Identification",
                "length": "35x",
                "description": "계좌 식별",
                "required": True,
            },
            {
                "field": ":28C",
                "name": "Statement Number",
                "length": "5n",
                "description": "명세서 번호",
                "required": False,
            },
        ],
    },
    "MT298": {
        "category": "9",
        "name": "Queue Message",
        "description": "대기열 메시지",
        "required_fields": [":20"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":95P",
                "name": "Party Identification",
                "length": "x",
                "description": "당사자 식별",
                "required": False,
            },
            {
                "field": ":34",
                "name": "Priority",
                "length": "4!c",
                "description": "우선순위",
                "required": False,
            },
        ],
    },
    "MT299": {
        "category": "9",
        "name": "Acknowledgement Message",
        "description": "확인 메시지",
        "required_fields": [":20"],
        "fields": [
            {
                "field": ":20",
                "name": "Transaction Reference",
                "length": "16x",
                "description": "트랜잭션 참조",
                "required": True,
            },
            {
                "field": ":21",
                "name": "Related Reference",
                "length": "16x",
                "description": "관련 참조",
                "required": False,
            },
            {
                "field": ":25",
                "name": "Account Identification",
                "length": "35x",
                "description": "계좌 식별",
                "required": False,
            },
        ],
    },
}
